### ISSUE TITLE
Media Error Occured on fetching playlist

### ISSUE THREAD

**Issue by tarioch** [memen45/SubMusic#1]
I just installed the app today and when I'm trying to sync I'm getting the error "Media Error Occured" when it's trying to fetch the playlist.

My setup is

server address: http://myhost.com:44
username: myuser
api key: mypassword

I'm running airsonic which works very well with all other subsonic clients: https://airsonic.github.io/

One thing that I found a bit weird is that on the config page, it shows "alpha 0.0.1" but as I installed today I think it should be 0.0.3 .

I'm using a vivoactive 4

**Comment by memen45** [comment]
Thank you for trying the app and providing feedback! 

As far as I know, it is not possible to use other ports than the default http and https ports. The "Media Error Occured" throws due to the ":"in the URL. If you can make your server available over http or https, it should start working. I have only tested with HTTPS (port 443) though, and I have seen issues with others trying to connect using HTTP, so let me know if http works too.

With regards to your second remark: you are completely right! I fixed it locally, but didn't push an update for it yet.

**Comment by tarioch** [comment]
Thanks for your quick feedback. I now tried with http://my.host.com (I only need the one with port when I'm outside my wlan and as the sync happens only in the wlan anyway it's good enough) and I'm still getting the media error.

**Comment by tarioch** [comment]
Is there any way to add some more logging/debugging to it to figure out what's failing?
Also have you thought about wheter you want to keep the app closed source or making it open source?

**Comment by memen45** [comment]
Are you able to get a response if you use "http://my.host.com/rest/ping" in the browser? The browser should show some XML response if the URL is working (right click -> view source).
If that does work, "http://my.host.com" as URL should work as well and not throw an error,

If the error remains, there should be something wrong in the code. If you are willing to help debug, there should be a file called CIQ_LOG.YAML in /GARMIN/APPS/LOGS on the device. It should provide a cause of error and a stack trace that could help me solve it.

**Comment by tarioch** [comment]
ping request works, log has exception in it

```

---
Error: Unhandled Exception
Time: 2020-06-10T11:07:19Z
Part-Number: 006-B3225-00
Firmware-Version: '4.70'
Language-Code: eng
ConnectIQ-Version: 3.1.8
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 2
Filename: A6A85331
Appname: SubMusic
Stack: 
  - pc: 0x100018df
---
Error: Unhandled Exception
Time: 2020-06-10T11:07:19Z
Part-Number: 006-B3225-00
Firmware-Version: '4.70'
Language-Code: eng
ConnectIQ-Version: 3.1.8
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 2
Filename: A6A85331
Appname: SubMusic
Stack: 
  - pc: 0x100018df
```

**Comment by tarioch** [comment]
Response for the ping rest call (after adding required params), so it was

http://my.host.com/rest/ping?u=myuser&p=mypassword&c=foo&v=1.15

```xml
<subsonic-response xmlns="http://subsonic.org/restapi" status="ok" version="1.15.0"/>
```

**Comment by memen45** [comment]
Hmm, unfortunately the stack trace is not too comprehensive. The URL seems fine though. I do see however that I missed the required parameters "c" and "v", as Nextcloud does not require them.
If you leave the c and v parameters, do you get a subsonic-response  - status="failed"?

I am not planning on keeping the app closed source at all. I wanted to clean up one part of the code before publishing as it is only functional, but not good code (still too much based on some example code). As soon as I have time to rewrite it, I will publish the code in this repository.

**Comment by tarioch** [comment]
After another couple of reinstalls and avoiding different playlists and files which are problematic (as you said, path does actually not make any troubles, I guess that was just caused by earlier issues). I was now able to sync a playlist with 27 songs in it :) Adding one more makes it fail. Are your playlists so short or does the nextcloud impl add less metadata?

Anyway, I think this is great progress (from not able to connect, to able to sync 27 songs in a playlist). Thank you again very much. 

Do you see any way to work around the issue with the response size of the getPlaylist?

**Comment by memen45** [comment]
Indeed I only tested with ~10 songs per playlist. Unfortunately the response limit is very low, somewhere around 16kB or 32kB. There is no simple way around this currently. 

I have made an update again:
 - default format=mp3 is requested
 - if stream failed, the song will be skipped (for all subsequent syncs) and continues to next song
 - removing a playlist that was not yet synced, will remove it from to_sync (so accidentally adding a too large playlist does no longer require reinstall)

Will upload it shortly (Version 0.0.9).

**Comment by tarioch** [comment]
Sound's great (do you never sleep? ;)). Is there a way to "stream" the response? As there isn't too much info needed from that response if there would be a way to work on the response stream, that might solve the issue.

**Comment by tarioch** [comment]
Started a thread on the forum to see if anyone has an idea, if we could stream it, I think it would be possible to handle it
https://forums.garmin.com/developer/connect-iq/f/discussion/229268/way-to-receive-web-request-response-as-a-stream

**Comment by memen45** [comment]
I don't think that is possible. Also other options like bluetooth etc are not possible due to the same memory limitation.

The most feasible option would be to add support for Ampache API. Looks much better and allows paged requests on almost all methods. Will look into this when I have more time.

Thanks a lot for the efforts on investigating! I will close this issue as the initial problem is fixed.

**Comment by tarioch** [comment]
Can you tell me the necessary stuff that you need on that getPlaylist call? I'm thinking about creating a small proxy that will do the real request and then strip out all the unnecessary stuff, that way it should reduce the response quite a bit, so I can also sync larger playlists.

**Comment by memen45** [comment]
The metadata should be delivered on downloading the song itself. Up to now, only the playlist name is shown to the user. Therefore for the getPlaylist request, the only thing required of each of the songs are the "id" elements. If you strip all the other elements from the song objects, I think it will take a while before you hit the limit again!

**Comment by tarioch** [comment]
If anyone is interested, I started creating it https://github.com/tarioch/subsonic-api-proxy still testing a bit more, I also want to something to have all the files as mp3, as in my setup the stream api will always return mp3 independent of the filename or metadata of the file, because of the on the fly conversion.
